### ISSUE TITLE
Test that all mitigators are functioning as expected

### ISSUE THREAD

**Issue by ChrisBeeley** [The-Strategy-Unit/nhp_data#2]

**Comment by tomjemmett** [comment]
@yiwen-h I believe that we have now agreed that this is the case, please re-open if not.

any differences we have encounted are listed here https://github.com/The-Strategy-Unit/nhp_data/blob/a2407548ddf2b9061a00e566f9fd8322522d6c7e/check_inpatients_mitigators.py#L51
